export const API = {
    REGISTER: 'auth/signup',
    SIGNIN: 'auth/signin',
    SIGNOUT: 'auth/signout',
    TOKEN: 'auth/token',
    CHECK_TOKEN: 'auth/checkToken',
    RESET_PASSWORD: 'auth/resetPassword',
    RESET_NEW_PASSWORD: 'auth/resetNewPassword',
    USER: 'user',
    USER_SERVICE: 'user/service',
    SERVICE: 'service',
    THEMATIC: 'thematic',
    TIMELINE: 'timeline',
    TIMELINE_FILTERED: 'timeline/filter',
    TIMELINE_LIST: 'timeline/list',
    ASSOCIATION: 'association',
};
